44 cached recording config
Sensors-in-Paradise/UnicornML pull request #45
Opened 2022-05-06 09:50 UTC by tfiedlerdev

This branch adds a new data config that loads the sonar data set with only 22 activities

2022-05-06 09:57 UTC, tfiedlerdev commented
Hab jetzt ausversehen mein Experiement doch reingepusht hier. Sollte ja aber kein Problem sein als seperates Experiment

2022-05-09 09:25 UTC, kpostnov commented on src/utils/Recording.py
> +        print(activities[0])
```suggestion

```

2022-05-09 09:37 UTC, kpostnov requested changes
See above.

2022-05-10 11:12 UTC, treyfel approved these changes

2022-05-11 07:56 UTC, kpostnov approved these changes

2022-05-12 09:37 UTC, merged